apiVersion: batch/v1
kind: Job

metadata:
   name: myjob

spec:
  template:
    metadata:
        name: testjob

    spec:
      containers:
        - name: mycont
          image: centos
          command: ["/bin/bash", "-c", "echo giri; sleep 15"]
      restartPolicy: Never
