kind: Deployment
apiVersion: apps/v1

metadata:
  name: mydeployments

spec:
  replicas: 3
  selector:
    matchLabels:
      objtype: deployment

  template:
    metadata:
      labels:
        objtype: deployment

    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c", "while true; do echo Hello-Satish; sleep 5; done"]
          resources:
            requests:
              cpu: "400m"
              memory: "400Mi"
